'use strict';

const { PUBLIC_BASE_URL } = require('./app');

const YOUTUBE_CLIENT_ID = String(process.env.YOUTUBE_CLIENT_ID || '').trim();
const YOUTUBE_CLIENT_SECRET = String(process.env.YOUTUBE_CLIENT_SECRET || '').trim();
const YOUTUBE_REDIRECT_URI = `${PUBLIC_BASE_URL}/auth/youtube/callback`;
const YOUTUBE_BROADCASTER_CHANNEL_ID = String(process.env.YOUTUBE_BROADCASTER_CHANNEL_ID || 'UCtEfKCmCxHi1NZ5npTvEuBg').trim();
const YOUTUBE_BROADCASTER_HANDLE = String(process.env.YOUTUBE_BROADCASTER_HANDLE || 'generalqwert').replace(/^@/, '').trim();
const YOUTUBE_SCOPE = 'https://www.googleapis.com/auth/youtube.force-ssl';
const YOUTUBE_MAIN_DAILY_LIMIT = 10000;
const YOUTUBE_SEARCH_DAILY_LIMIT = 100;
const YOUTUBE_INSERT_COST = 50;
const YOUTUBE_LIST_COST = 1;
const YOUTUBE_INITIAL_DISCOVERY_DELAY_MS = 2500;
const YOUTUBE_DISCOVERY_DELAYS_MS = Object.freeze(
  [0, 15000, 30000, 60000, 120000, 300000].map((delay) => delay + YOUTUBE_INITIAL_DISCOVERY_DELAY_MS)
);

module.exports = {
  YOUTUBE_CLIENT_ID,
  YOUTUBE_CLIENT_SECRET,
  YOUTUBE_REDIRECT_URI,
  YOUTUBE_BROADCASTER_CHANNEL_ID,
  YOUTUBE_BROADCASTER_HANDLE,
  YOUTUBE_SCOPE,
  YOUTUBE_MAIN_DAILY_LIMIT,
  YOUTUBE_SEARCH_DAILY_LIMIT,
  YOUTUBE_INSERT_COST,
  YOUTUBE_LIST_COST,
  YOUTUBE_INITIAL_DISCOVERY_DELAY_MS,
  YOUTUBE_DISCOVERY_DELAYS_MS
};
